import Head from "next/head";
import Image from "next/image";
import Main from "./main";
// import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Neocon Group Limited</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      {/* <p className="text-text_56 text-ngl_orange">fahad</p> */}
    </>
  );
}
